"""
Idempotent .gitignore marker-block helper for mill-setup Phase 4.5b.

Writes and maintains a ``# === mill-managed ... # === end mill-managed ===``
block at the end of the repo's ``.gitignore``. The block covers standard
mill paths and every hardlink entry declared in ``wiki/config.yaml``.

Outside-marker content is NEVER modified. Duplicate entries that already
exist outside the markers are left alone.

Public API:
    render_block(hardlink_entries)
        Return the full marker-block text for the given hardlink entry names.
    upsert(gitignore_path, hardlink_entries)
        Write or rewrite the marker block at the end of the file. Returns
        True if the file changed, False if it was already byte-equal.

Constants:
    START   — opening marker line
    END     — closing marker line
    STANDARD_ENTRIES — paths always present inside the block
"""
from __future__ import annotations

from pathlib import Path

START = "# === mill-managed (regenerated by mill-setup) ==="
END = "# === end mill-managed ==="

STANDARD_ENTRIES: list[str] = [
    "**/.millhouse/",
    "**/.scratch/",
    "**/worktrees/",
    "/.active",
]


def render_block(hardlink_entries: list[str]) -> str:
    """
    Return the marker-block text for the given hardlink entry names.

    Each hardlink entry name is normalised to have a leading ``/`` so it
    is anchored at the repository root (e.g. ``tasks.md`` → ``/tasks.md``).
    Standard mill entries always appear first; hardlink entries follow.

    Args:
        hardlink_entries: Bare entry names from ``wiki/config.yaml``'s
            ``hardlinks:`` block (e.g. ``["tasks.md"]``). Names that
            already start with ``/`` are kept as-is.

    Returns:
        Multi-line string starting with ``START`` and ending with
        ``END\\n``. Each entry occupies its own line.
    """
    lines = [START]
    for entry in STANDARD_ENTRIES:
        lines.append(entry)
    for entry in hardlink_entries:
        normalised = entry if entry.startswith("/") else f"/{entry}"
        lines.append(normalised)
    lines.append(END)
    return "\n".join(lines) + "\n"


def upsert(gitignore_path: Path, hardlink_entries: list[str]) -> bool:
    """
    Write or rewrite the mill marker block at the end of ``.gitignore``.

    Locates the existing ``START`` / ``END`` markers (if any), removes the
    old block including the blank-line separator that precedes it, and
    appends the freshly-rendered block. If no prior block exists the block
    is appended with a blank-line separator.

    Returns True if the file was written (content changed), False if the
    file was already byte-equal to what would be written.

    Args:
        gitignore_path: Path to the ``.gitignore`` file. The file is
            created if it does not exist.
        hardlink_entries: Bare entry names for the hardlinks block (see
            ``render_block``).

    Raises:
        ValueError: ``START`` marker is present but ``END`` marker is
            absent — the file is in a corrupt/partial state that cannot
            be repaired automatically.
    """
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
    else:
        existing = ""

    start_idx = existing.find(START)
    end_idx = existing.find(END)

    if start_idx != -1 and end_idx == -1:
        raise ValueError(
            f"Found START marker but no END marker in {gitignore_path}. "
            "The file appears corrupt — remove the partial block manually and re-run."
        )

    new_block = render_block(hardlink_entries)

    if start_idx != -1:
        # Strip the old block from start_idx onwards (and the blank line
        # separator that precedes the block, if present).
        prefix = existing[:start_idx]
        # Remove one trailing blank line from the prefix so the separator
        # is not doubled on rewrite.
        stripped_prefix = prefix.rstrip("\n")
        rebuilt = stripped_prefix + "\n\n" + new_block if stripped_prefix else new_block
    else:
        # No prior block — append with blank-line separator.
        stripped = existing.rstrip("\n")
        rebuilt = stripped + "\n\n" + new_block if stripped else new_block

    if rebuilt == existing:
        return False

    gitignore_path.write_text(rebuilt, encoding="utf-8")
    return True
