"""
Idempotent .gitignore marker-block helper for mill-setup Phase 4.5b.

Writes and maintains a ``# === mill-managed ... # === end mill-managed ===``
block at the end of the repo's ``.gitignore``. The block covers standard
mill paths and every hardlink entry declared in ``wiki/config.yaml``.

Outside-marker content is NEVER modified. Duplicate entries that already
exist outside the markers are left alone.

Public API:
    render_block(glob_entries, anchored_entries)
        Return the full marker-block text. ``glob_entries`` are written
        first (as-is); ``anchored_entries`` follow, each normalised to a
        leading ``/``.
    upsert_split(repo_root_gitignore, hub_gitignore, glob_entries, anchored_entries)
        Two-path write. When both paths are the same, writes a single combined
        block. When different, writes glob entries to ``repo_root_gitignore``
        and anchored entries to ``hub_gitignore``. Returns ``(repo_changed,
        hub_changed)``.

Constants:
    START            — opening marker line
    END              — closing marker line
    GLOB_ENTRIES     — glob-pattern entries always written to the repo root gitignore
    ANCHORED_ENTRIES — root-anchored entries written to the hub gitignore
"""
from __future__ import annotations

from pathlib import Path

START = "# === mill-managed (regenerated by mill-setup) ==="
END = "# === end mill-managed ==="

GLOB_ENTRIES: list[str] = [
    "**/.millhouse/",
    "**/.scratch/",
    "**/wts/",
    "**/portals/",
    "**/plugins/*/uv.lock",
]

ANCHORED_ENTRIES: list[str] = [
    "/.active",
    "/.others",
]


def render_block(glob_entries: list[str], anchored_entries: list[str]) -> str:
    """
    Return the marker-block text.

    ``glob_entries`` are written first, each as-is. ``anchored_entries``
    follow, each normalised to a leading ``/``.

    Args:
        glob_entries: Glob-pattern entries (e.g. ``GLOB_ENTRIES``).
        anchored_entries: Root-anchored entries (e.g. ``ANCHORED_ENTRIES``).
            Each entry is normalised to a leading ``/``.

    Returns:
        Multi-line string starting with ``START`` and ending with
        ``END\\n``.
    """
    lines = [START]
    for entry in glob_entries:
        lines.append(entry)
    for entry in anchored_entries:
        normalised = entry if entry.startswith("/") else f"/{entry}"
        lines.append(normalised)
    lines.append(END)
    return "\n".join(lines) + "\n"


def _upsert_single(gitignore_path: Path, block_text: str) -> bool:
    """Write or rewrite a marker block in a single .gitignore file.

    Locates the existing ``START`` / ``END`` markers (if any), removes the
    old block and its blank-line separator, and appends the new block. If no
    prior block exists the block is appended with a blank-line separator.

    Returns True if the file was written (content changed), False if already
    byte-equal.

    Raises:
        ValueError: ``START`` is present but ``END`` is absent — the file is
            in a corrupt/partial state that cannot be repaired automatically.
    """
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
    else:
        existing = ""

    start_idx = existing.find(START)
    end_idx = existing.find(END)

    if start_idx != -1 and end_idx == -1:
        raise ValueError(
            f"Found START marker but no END marker in {gitignore_path}. "
            "The file appears corrupt — remove the partial block manually and re-run."
        )

    if start_idx != -1:
        prefix = existing[:start_idx]
        stripped_prefix = prefix.rstrip("\n")
        rebuilt = stripped_prefix + "\n\n" + block_text if stripped_prefix else block_text
    else:
        stripped = existing.rstrip("\n")
        rebuilt = stripped + "\n\n" + block_text if stripped else block_text

    if rebuilt == existing:
        return False

    gitignore_path.write_text(rebuilt, encoding="utf-8")
    return True


def upsert_split(
    repo_root_gitignore: Path,
    hub_gitignore: Path,
    glob_entries: list[str],
    anchored_entries: list[str],
) -> tuple[bool, bool]:
    """
    Write or rewrite mill marker blocks, optionally split across two files.

    When ``repo_root_gitignore == hub_gitignore`` (hub is the repo root),
    writes a single combined block — glob entries then anchored entries —
    and returns ``(changed, False)``.

    When the paths differ (hub is a sub-directory of the repo), writes glob
    entries only to ``repo_root_gitignore`` and anchored entries only to
    ``hub_gitignore``, returning ``(repo_changed, hub_changed)``.

    Idempotent: a re-run on already-correct files returns ``(False, False)``.

    Args:
        repo_root_gitignore: Path to the repo-root ``.gitignore``.
        hub_gitignore: Path to the hub-directory ``.gitignore``. Equals
            ``repo_root_gitignore`` for the typical case where hub == repo root.
        glob_entries: Glob-pattern entries (e.g. ``GLOB_ENTRIES``). Written
            to ``repo_root_gitignore`` (and also ``hub_gitignore`` when equal).
        anchored_entries: Root-anchored entries (e.g. ``ANCHORED_ENTRIES``).
            Written to ``hub_gitignore`` (and also ``repo_root_gitignore``
            when equal).

    Returns:
        ``(repo_changed, hub_changed)`` — True for each file that was written.

    Raises:
        ValueError: START marker present but END marker absent in either file.
    """
    if repo_root_gitignore == hub_gitignore:
        block = render_block(glob_entries, anchored_entries)
        changed = _upsert_single(repo_root_gitignore, block)
        return (changed, False)

    glob_block = render_block(glob_entries, [])
    anchored_block = render_block([], anchored_entries)
    repo_changed = _upsert_single(repo_root_gitignore, glob_block)
    hub_changed = _upsert_single(hub_gitignore, anchored_block)
    return (repo_changed, hub_changed)
