"""
Idempotent .gitignore marker-block helper for mill-setup Phase 4.5b.

Writes and maintains a ``# === mill-managed ... # === end mill-managed ===``
block at the end of the repo's ``.gitignore``. The block covers standard
mill paths declared in ``GLOB_ENTRIES``.

Outside-marker content is NEVER modified. Duplicate entries that already
exist outside the markers are left alone.

Public API:
    render_block(glob_entries)
        Return the full marker-block text. ``glob_entries`` are written as-is.
    upsert(gitignore_path, glob_entries)
        Write or rewrite the marker block in a single ``.gitignore`` file.
        Returns ``True`` if the file was written (content changed), ``False``
        if already byte-equal.

Constants:
    START        — opening marker line
    END          — closing marker line
    GLOB_ENTRIES — glob-pattern entries always written to the repo root gitignore
"""
from __future__ import annotations

from pathlib import Path

START = "# === mill-managed (regenerated by mill-setup) ==="
END = "# === end mill-managed ==="

GLOB_ENTRIES: list[str] = [
    "**/.millhouse/",
    "**/.scratch/",
    "**/.wiki/",
    "**/.active/",
    "**/.portals/",
]


def render_block(glob_entries: list[str]) -> str:
    """
    Return the marker-block text.

    ``glob_entries`` are written as-is between the START and END markers.

    Args:
        glob_entries: Glob-pattern entries (e.g. ``GLOB_ENTRIES``).

    Returns:
        Multi-line string starting with ``START`` and ending with
        ``END\\n``.
    """
    lines = [START]
    for entry in glob_entries:
        lines.append(entry)
    lines.append(END)
    return "\n".join(lines) + "\n"


def _upsert_single(gitignore_path: Path, block_text: str) -> bool:
    """Write or rewrite a marker block in a single .gitignore file.

    Locates the existing ``START`` / ``END`` markers (if any), removes the
    old block and its blank-line separator, and appends the new block. If no
    prior block exists the block is appended with a blank-line separator.

    Returns True if the file was written (content changed), False if already
    byte-equal.

    Raises:
        ValueError: ``START`` is present but ``END`` is absent — the file is
            in a corrupt/partial state that cannot be repaired automatically.
    """
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
    else:
        existing = ""

    start_idx = existing.find(START)
    end_idx = existing.find(END)

    if start_idx != -1 and end_idx == -1:
        raise ValueError(
            f"Found START marker but no END marker in {gitignore_path}. "
            "The file appears corrupt — remove the partial block manually and re-run."
        )

    if start_idx != -1:
        prefix = existing[:start_idx]
        stripped_prefix = prefix.rstrip("\n")
        rebuilt = stripped_prefix + "\n\n" + block_text if stripped_prefix else block_text
    else:
        stripped = existing.rstrip("\n")
        rebuilt = stripped + "\n\n" + block_text if stripped else block_text

    if rebuilt == existing:
        return False

    gitignore_path.write_text(rebuilt, encoding="utf-8")
    return True


def upsert(gitignore_path: Path, glob_entries: list[str]) -> bool:
    """
    Write or rewrite the mill marker block in a single ``.gitignore`` file.

    Renders the block via ``render_block(glob_entries)`` and delegates to
    ``_upsert_single``.

    Args:
        gitignore_path: Path to the ``.gitignore`` file to update.
        glob_entries: Glob-pattern entries (e.g. ``GLOB_ENTRIES``).

    Returns:
        ``True`` if the file was written (content changed), ``False`` if
        already byte-equal.

    Raises:
        ValueError: START marker present but END marker absent in the file.
    """
    block = render_block(glob_entries)
    return _upsert_single(gitignore_path, block)
