"""
mill-skills-index — scan plugins/*/skills/**/SKILL.md and regenerate SKILLS.md.

Reads YAML frontmatter (`name`, `description`) from every SKILL.md under
`<hub>/plugins/*/skills/`, builds a single `SKILLS.md` at hub root with one
row per skill, sorted alphabetically per plugin.

Usage (from hub root):
    python plugins/mill/scripts/mill-skills-index.py

Exits 0 on success, 1 on error (e.g. called from outside a git repo).

Writes use `newline="\\n"` so Windows does not translate LF to CRLF; that
keeps re-runs byte-identical across platforms.
"""
from __future__ import annotations

import _subprocess_util
import sys
from pathlib import Path

import yaml


def _repo_root() -> Path:
    """Return the hub repo root via `git rev-parse --show-toplevel`."""
    result = _subprocess_util.run(
        ["git", "rev-parse", "--show-toplevel"],
    )
    if result.returncode != 0:
        raise RuntimeError(f"not a git repo: {result.stderr.strip()}")
    return Path(result.stdout.strip()).resolve()


def _extract_frontmatter(text: str) -> dict | None:
    """Return parsed YAML frontmatter from text, or None if absent/malformed.

    Frontmatter is the block delimited by `---` lines at the very top of
    the file. This matches the SKILL.md convention — it is the one place
    `---` frontmatter is allowed by the markdown skill.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            try:
                return yaml.safe_load("\n".join(lines[1:i])) or {}
            except yaml.YAMLError:
                return None
    return None


def _scan(repo_root: Path) -> dict[str, list[dict]]:
    """Scan plugins/*/skills/**/SKILL.md; return {plugin: [entries]}.

    Each entry: {name, description, path (posix, hub-relative)}.
    Sorted by name per plugin. Plugins in alphabetic order.
    """
    out: dict[str, list[dict]] = {}
    plugins_dir = repo_root / "plugins"
    if not plugins_dir.is_dir():
        return out

    for plugin_dir in sorted(p for p in plugins_dir.iterdir() if p.is_dir()):
        skills_dir = plugin_dir / "skills"
        if not skills_dir.is_dir():
            continue
        entries: list[dict] = []
        for skill_md in sorted(skills_dir.rglob("SKILL.md")):
            try:
                text = skill_md.read_text(encoding="utf-8")
            except OSError as exc:
                print(f"[skills-index] skip {skill_md}: {exc}", file=sys.stderr)
                continue
            fm = _extract_frontmatter(text)
            if fm is None or "name" not in fm or "description" not in fm:
                print(
                    f"[skills-index] skip {skill_md}: missing frontmatter",
                    file=sys.stderr,
                )
                continue
            entries.append({
                "name": str(fm["name"]).strip(),
                "description": str(fm["description"]).replace("\n", " ").strip(),
                "path": skill_md.relative_to(repo_root).as_posix(),
            })
        if entries:
            out[plugin_dir.name] = sorted(entries, key=lambda e: e["name"])
    return out


def _render(scan: dict[str, list[dict]]) -> str:
    """Render the combined SKILLS.md content."""
    parts: list[str] = [
        "# Skills",
        "",
        "Generated by `mill-skills-index`. Do not edit by hand — rerun the "
        "script after adding or renaming a skill.",
        "",
    ]
    for plugin, entries in scan.items():
        parts.append(f"## {plugin}")
        parts.append("")
        parts.append("| Skill | Description |")
        parts.append("|---|---|")
        for entry in entries:
            parts.append(f"| [{entry['name']}]({entry['path']}) | {entry['description']} |")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    try:
        root = _repo_root()
    except RuntimeError as exc:
        print(f"[skills-index] {exc}", file=sys.stderr)
        return 1

    scan = _scan(root)
    total = sum(len(v) for v in scan.values())

    target = root / "SKILLS.md"
    target.write_text(_render(scan), encoding="utf-8", newline="\n")

    print(
        f"[skills-index] wrote {target.name} "
        f"({total} skill(s) across {len(scan)} plugin(s))"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
