"""
Shortcut wrapper for <SCRIPT>.

Locates the latest installed millhouse plugin cache, inserts the scripts
directory into sys.path, and delegates to the real <SCRIPT>.py via
runpy.run_path so hyphenated script names are not treated as import paths.

Generated by mill-setup Phase 4.7. Do not edit manually — re-run mill-setup.
"""
import pathlib
import runpy
import sys

_cache = pathlib.Path.home() / ".claude" / "plugins" / "cache" / "millhouse" / "mill"

if not _cache.exists():
    print(f"[mill] error: plugin cache not found at {_cache}", file=sys.stderr)
    sys.exit(1)

_semver_dirs = sorted(
    [d for d in _cache.iterdir() if d.is_dir()],
    key=lambda d: d.name,
    reverse=True,
)

if not _semver_dirs:
    print(f"[mill] error: no versioned plugin directories found under {_cache}", file=sys.stderr)
    sys.exit(1)

_scripts = _semver_dirs[0] / "scripts"
sys.path.insert(0, str(_scripts))

runpy.run_path(str(_scripts / "<SCRIPT>.py"), run_name="__main__")
