# Wrapper for <SCRIPT> — generated by mill-setup Phase 4.7. Do not edit manually — re-run mill-setup.
$cache = "$HOME\.claude\plugins\cache\millhouse\mill"
$latest = (Get-ChildItem $cache -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName
if (-not $latest) { Write-Error "[mill] plugin cache not found at $cache"; exit 1 }
uv run --project $latest "$latest\scripts\<SCRIPT>.py" @args
